### PR TITLE
Added a gulp build system

### PR DESCRIPTION
**Pull request by BurkovBA**
Simon, considering the #45 issue, I took the liberty to create a simple `Gulpfile` configuration for building bundles of Genoverse. It is a copy-paste of Addy Osmani's [google/web-starter-kit](https://github.com/google/web-starter-kit) gulpfile with some omissions and simplifications.

I tried to comment it as well as I could. If anything about it is unclear, please, let me know.

To run it you need to globally install `npm install -g gulp-cli` and locally install `devDependencies` with `npm install`.

Then run it with `gulp <task>`, where `<task>` is one of the tasks in the list below. Task can be empty - this will run the default task that generates minified bundles in `/dist` folder. You can also run default task with `npm run gulp` - I added `gulp` target to `package.json` `scripts` section.

All the tasks output their results into `/dist` folder in the root of repository and use `/.tmp` directory for temporary files. Here's the list:

- `styles`  task builds css assets (adding autoprefixes and uglifying them);
- `fonts` and `images` tasks just copy-paste fonts and images from source to `.tmp` and `dist` folders
- `scripts:all` tasks builds full bundle with dependencies (jquery and its plugins and jquery-ui) and Genoverse plugins
- `scripts:nodeps` task builds Genoverse bundle without jquery and friends and without Genoverse plugins
- `clean` task cleans `/.tmp` and `/dist` folders
- `serve` task copies Genoverse source files into `/.tmp` folder and serves them with Browsersync
- `serve:dist` task serves Genoverse minified bundles from `/dist` folder with Browsersync

I tested that `serve` and `serve:dist` targets display `index.html` page with Genoverse and without any errors, using source files and minified bundles, respectively. 

I hope, you wouldn't mind against adding this Gulpfile. It adds ~15 dependencies to `devDependencies`, but I feel like this additional complexity is justified by the functionality and readability it brings to the table. 

I considered going with plain `npm scripts` instead of `Gulp`, but from my experiences it's a far worse solution for libraries - error-prone and hard to maintain.

Thank you!

### CODE REVIEW

**Comment by simonbrent** [comment]
There are a couple of issues with this that I can see:

1) I think it is unreasonable to remove plugins from the nodeps version. There is a likely use-case where the site already has jquery loaded, but that doesn't automatically mean that that site would not want plugins (historically, plugins were loaded asynchronously because having them present automatically caused them to be used, but this is no longer the case).

2) jquery and jquery.ui are obvious candidates to remove from the build. jquery.mousewheel, jquery.mousehold (which isn't on npm, FYI), and jquery.tipsy are less obvious. Without them, some things will not work as expected, and it would not be immediately obvious as to why this is.

**Comment by BurkovBA** [comment]
Simon, I acted upon your notes:

1. Ok, thanks for notice, I added plugins to `nodeps` version.
2. No problem - I created a [repo for jquery.mousehold](https://github.com/BurkovBA/jquery-mousehold) plugin and will publish it tomorrow (by accident I published another package of the same name today and had to unpublish it, so now I can't publish the correct version within 24 hours). All the other packages are available from npm. 

There are slight variations in versions though: `tipsy` in your `lib` folder is of a strange non-semver version `1.0.0a` - I used 1.0.3 instead. `jquery.mousewheel` in your `lib` folder is 3.0.6, I bumped it to the latest 3.1.9.

**Comment by simonbrent** [comment]
This has failed to build. I assume because jquery.mousehold is not on npm right now, but I'm unsure (the error messages from Travis are super unhelpful).

I'm also still not sure this helps with the dependencies issue, as the nodeps version will still require people to know that they need to manually add mousehold, mousewheel and tipsy in order for things to work properly.

**Comment by BurkovBA** [comment]
Yep, let's wait for a day - I'll create jquery.mousehold package and publish it.

As for `.nodeps` version requiring installation of dependencies... 

Well, I looked through `package.json` of most popular libraries and indeed it's not a common practice for them to list dependencies. One example that came to my mind immediately was [Backbone that specifies underscore as a dependency](https://github.com/jashkenas/backbone/blob/master/package.json).

Another example is Bootstrap that specifies `jquery` and `popper` as peerDependencies. Bootstrap [is distributed in a version without jquery and in a bundle version with popper](https://www.npmjs.com/package/bootstrap) (but still without jquery).

Maybe, it makes sense to rename `dependencies` -> `peerDependencies` in Genoverse package.json or even use bundledDependencies. See the following posts about their differences:

- https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies
- https://nodejs.org/en/blog/npm/peer-dependencies/
- https://stackoverflow.com/questions/11207638/advantages-of-bundleddependencies-over-normal-dependencies-in-npm?lq=1

Thing is, this whole dependencies concept was meant for backend packages and node.js.

When they used to install frontend packages with Bower, it was `bower.json`'s `dependencies` field that specified those upstream libraries (in `bower.json`, `jquery` would've been in `dependencies` of Genoverse and everybody would've known, what to do). 

But now that they distribute both frontend and backend packages via NPM, it's a bit messed up. So, maybe, it makes sense to rename current `dependencies` to `peerDependencies` and go with it.

**Comment by BurkovBA** [comment]
I think, I need to explicitly say, why a version of Genoverse without upstream dependencies is needed.

Imagine that everyone started to bundle their own version of jquery with their library. 

Then consider libraries `lib1` and `lib2`, coming with their jqueries and you're importing both in your index.html:

`index.html`:
```
<script src="lib1.js"></script> <!-- contains jquery==3.2.1 -->
<script src="lib2.js"></script> <!-- contains jquery==3.0.0 -->
```
jquery3.0.0 from the second library would overshadow jquery 3.2.1 from first library. If first library was a jquery plugin, modifying `$.fn` of jquery==3.2.1 - that's it - after the import of `lib2.js` `lib1.js` is gone.

That's what's happening with Genoverse for me.

**Comment by simonbrent** [comment]
I am in absolute agreement that a version without jquery and jquery.ui is beneficial (and in fact this existed until quite recently). I am purely arguing that removing the other jquery plugins from this version is maybe not such a good idea, due to potential bugs and confusion.

**Comment by BurkovBA** [comment]
Ok, I published jquery.mousehold npm package (and moved dependencies to peerDependencies anyways), so the build runs fine now.

**Comment by BurkovBA** [comment]
Hi, Simon, an update:

I checked that `genoverse.min.nodeps.js` and all its dependencies (installed separately) result in a correct build.

I had to rename `genoverse.nodeps.min.js` into `genoverse.min.nodeps.js`, cause otherwise Genoverse doesn't recognize `Genoverse.origin` correctly and tries to load genomes from a wrong location.

I also moved the dependencies (jquery, jquery-ui, jquery.mousewheel, jquery.mousehold and tipsy) from `peerDependencies` to `devDependencies`, cause to minimise the amount of headache.

So, real-life test of this PR was successful.

**Pull request closed without merging**
